//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalVideo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ACTOR_PELICULA
    {
        public int APL_ID { get; set; }
        [Display(Name = "Actor")]
        public Nullable<int> ACT_ID { get; set; }
        [Display(Name = "Película")]
        public Nullable<int> PEL_ID { get; set; }
        [Display(Name = "Papel")]
        public string APL_PAPEL { get; set; }
    
        public virtual ACTOR ACTOR { get; set; }
        public virtual PELICULA PELICULA { get; set; }
    }
}
