//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalVideo
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class SOCIO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SOCIO()
        {
            this.ALQUILER = new HashSet<ALQUILER>();
        }
    
        public int SOC_ID { get; set; }
        [Display(Name = "Cédula")]
        public string SOC_CEDULA { get; set; }
        [Display(Name = "Nombre")]
        public string SOC_NOMBRE { get; set; }
        [Display(Name = "Dirección")]
        public string SOC_DIRECCION { get; set; }
        [Display(Name = "Teléfono")]
        public string SOC_TELEFONO { get; set; }
        [Display(Name = "Correo")]
        public string SOC_CORREO { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ALQUILER> ALQUILER { get; set; }
    }
}
